// const products = [
//     {
//         _id: '1',
//         name: 'acer aspire3 ',
//         image:'https://m.media-amazon.com/images/I/61Fz7fTlBcL._SX679_.jpg',
//         description: 'good laptop for a astonishing price',
//         brand:'acer',
//         category:'buissness',
//         price:43000,
//         countInStock:3,
//         rating:4.5,
//         numReviews:4,
//     },
//     {
//         _id: '2',
//         name: 'acer Nitro',
//         image:'https://m.media-amazon.com/images/I/71evs2WKJjS._SX425_.jpg',
//         description: 'good laptop for a astonishing price',
//         brand:'acer',
//         category:'gaming',
//         price:63000,
//         countInStock:3,
//         rating:3.5,
//         numReviews:2,
//     },
//     {
//         _id: '3',
//         name: 'dell insperon ',
//         image:'https://m.media-amazon.com/images/I/719vIKTyr6L._SL1500_.jpg',
//         description: 'good laptop for a astonishing price',
//         brand:'dell',
//         category:'student',
//         price:33000,
//         countInStock:5,
//         rating:4,
//         numReviews:4,
//     },
//     {
//         _id: '4',
//         name: 'asus vivobook ',
//         image:'https://m.media-amazon.com/images/I/71S8U9VzLTL._SX679_.jpg',
//         description: 'good laptop for a astonishing price',
//         brand:'asus',
//         category:'buissness',
//         price:53000,
//         countInStock:8,
//         rating:5,
//         numReviews:4,
//     },
//     {
//         _id: '5',
//         name: 'hp probook ',
//         image:'https://m.media-amazon.com/images/I/81S0RJKddIL._SX679_.jpg',
//         description: 'good laptop for a astonishing price',
//         brand:'acer',
//         category:'buissness',
//         price:73000,
//         countInStock:8,
//         rating:2,
//         numReviews:4,
//     },
//     {
//         _id: '6',
//         name: 'mi horizen edition',
//         image:'https://m.media-amazon.com/images/I/713he67k8HL._SX679_.jpg',
//         description: 'good laptop for a astonishing price',
//         brand:'mi',
//         category:'buissness',
//         price:49000,
//         countInStock:8,
//         rating:3.5,
//         numReviews:4,
//     },

// ]


// export default products;